version: '3.8'
services:
  server-chat:
    build:
      context: ./server-chat-socketio
      dockerfile: Dockerfile
    image: server-chat-socketio-img
    container_name: server-chat-socketio
 
    volumes:
      - /app/node_modules
      - ./server-chat-socketio/:/app
    ports:
      - "4000:4000"
    depends_on:
      - mongo-chat
    env_file: ./server-chat-socketio/.env
    environment:
      - NODE_ENV=development
    networks:
      - chat-network

  mongo-chat:
    image: mongo
    volumes:
      -  mongo-chat-data-volume:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    restart: on-failure

    networks:
      - chat-network

  client-chat:
    build:
      context: ./client-chat-socketio
      dockerfile: Dockerfile
    image: myapp-client-chat
    container_name: myapp-react-client-chat
    volumes:
      - /app/node_modules
      - ./client-chat-socketio/:/app
    depends_on:
      - server-chat
    ports:
      - "3000:5173"
    networks:
      - chat-network
    stdin_open: true
    tty: true



networks:
    chat-network:
        driver: bridge

volumes:
    mongo-chat-data-volume:
    node_modules:
    web-root:
      driver: local